import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { logAudit } from "@/lib/audit";
import type { ContainerRow, Submission, WorkflowEvent } from "@/lib/workflow";

export type NotificationRow = {
  id: string;
  title: string;
  body: string | null;
  category: string;
  priority: "low" | "normal" | "high" | "critical";
  link: string | null;
  read_at: string | null;
  created_at: string;
};

/** Current user's notification feed (database-backed, generated by workflow triggers). */
export function useNotificationFeed(limit = 6) {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["notification-feed", user?.id, limit],
    enabled: !!user,
    staleTime: 15_000,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("notifications")
        .select("*")
        .is("archived_at", null)
        .order("created_at", { ascending: false })
        .limit(limit);
      if (error) throw new Error(error.message);
      return (data ?? []) as unknown as NotificationRow[];
    },
  });
}

/** Cross-shipment activity feed from workflow_events. */
export function useRecentEvents(limit = 12) {
  return useQuery({
    queryKey: ["workflow-events", limit],
    staleTime: 15_000,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("workflow_events")
        .select("*")
        .order("created_at", { ascending: false })
        .limit(limit);
      if (error) throw new Error(error.message);
      return (data ?? []) as unknown as WorkflowEvent[];
    },
  });
}

/** Submissions visible to the signed-in user (RLS decides scope). */
export function useAllSubmissions() {
  return useQuery({
    queryKey: ["submissions", "all"],
    staleTime: 15_000,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("shipment_submissions")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw new Error(error.message);
      return (data ?? []) as unknown as Submission[];
    },
  });
}

export function useAllContainers() {
  return useQuery({
    queryKey: ["containers", "all"],
    staleTime: 10_000,
    queryFn: async () => {
      const { data, error } = await supabase
        .from("containers")
        .select("*")
        .order("updated_at", { ascending: false });
      if (error) throw new Error(error.message);
      return (data ?? []) as unknown as ContainerRow[];
    },
  });
}

/** Register the declared container manifest for a submission. */
export function useRegisterContainers() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (args: { submission: Submission; count: number; prefix?: string }) => {
      const { data: existing } = await supabase
        .from("containers").select("container_no").eq("submission_id", args.submission.id);
      const taken = new Set((existing ?? []).map((c) => (c as { container_no: string }).container_no));
      const base = (args.prefix ?? args.submission.reference.replace(/[^A-Z0-9]/gi, "").toUpperCase()).slice(0, 8);
      const rows: Record<string, unknown>[] = [];
      let n = 1;
      while (rows.length < args.count) {
        const no = `${base}-${String(n).padStart(4, "0")}`;
        n += 1;
        if (taken.has(no)) continue;
        rows.push({
          submission_id: args.submission.id,
          container_no: no,
          hazardous: args.submission.dangerous_goods,
          stage: "at_vessel",
        });
        if (n > args.count + 500) break;
      }
      if (rows.length === 0) return 0;
      const { error } = await supabase.from("containers").insert(rows as never);
      if (error) throw new Error(error.message);
      await logAudit("data_created", {
        target_type: "container_manifest",
        target_id: args.submission.id,
        metadata: { created: rows.length, reference: args.submission.reference },
      });
      return rows.length;
    },
    onSuccess: () => { void qc.invalidateQueries({ queryKey: ["containers"] }); },
  });
}

/** Add one container manually. */
export function useAddContainer() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (row: Partial<ContainerRow> & { submission_id: string; container_no: string }) => {
      const { error } = await supabase.from("containers").insert(row as never);
      if (error) throw new Error(error.message);
    },
    onSuccess: () => { void qc.invalidateQueries({ queryKey: ["containers"] }); },
  });
}

export function useDeleteContainer() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase.from("containers").delete().eq("id", id);
      if (error) throw new Error(error.message);
      await logAudit("data_deleted", { target_type: "container", target_id: id });
    },
    onSuccess: () => { void qc.invalidateQueries({ queryKey: ["containers"] }); },
  });
}

/** Bulk patch a set of containers (yard, storage, truck, stage…). */
export function useBulkUpdateContainers() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (args: { ids: string[]; patch: Partial<ContainerRow> }) => {
      if (args.ids.length === 0) throw new Error("Select at least one container");
      const { error } = await supabase.from("containers").update(args.patch as never).in("id", args.ids);
      if (error) throw new Error(error.message);
      await logAudit("data_updated", {
        target_type: "container",
        target_id: args.ids.join(","),
        metadata: { count: args.ids.length, new_value: args.patch },
      });
    },
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ["containers"] });
      void qc.invalidateQueries({ queryKey: ["notification-feed"] });
    },
  });
}
