/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth.verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppWarehouseRouteImport } from './routes/app.warehouse'
import { Route as AppTruckRouteImport } from './routes/app.truck'
import { Route as AppTerminalRouteImport } from './routes/app.terminal'
import { Route as AppShippingRouteImport } from './routes/app.shipping'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPortAuthorityRouteImport } from './routes/app.port-authority'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppLogisticsRouteImport } from './routes/app.logistics'
import { Route as AppLiveMapRouteImport } from './routes/app.live-map'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppCustomsRouteImport } from './routes/app.customs'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWarehouseRoute = AppWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AppRoute,
} as any)
const AppTruckRoute = AppTruckRouteImport.update({
  id: '/truck',
  path: '/truck',
  getParentRoute: () => AppRoute,
} as any)
const AppTerminalRoute = AppTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AppRoute,
} as any)
const AppShippingRoute = AppShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPortAuthorityRoute = AppPortAuthorityRouteImport.update({
  id: '/port-authority',
  path: '/port-authority',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveMapRoute = AppLiveMapRouteImport.update({
  id: '/live-map',
  path: '/live-map',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomsRoute = AppCustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/customs': typeof AppCustomsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/live-map': typeof AppLiveMapRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/port-authority': typeof AppPortAuthorityRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipping': typeof AppShippingRoute
  '/app/terminal': typeof AppTerminalRoute
  '/app/truck': typeof AppTruckRoute
  '/app/warehouse': typeof AppWarehouseRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/customs': typeof AppCustomsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/live-map': typeof AppLiveMapRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/port-authority': typeof AppPortAuthorityRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipping': typeof AppShippingRoute
  '/app/terminal': typeof AppTerminalRoute
  '/app/truck': typeof AppTruckRoute
  '/app/warehouse': typeof AppWarehouseRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai': typeof AppAiRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/customs': typeof AppCustomsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/live-map': typeof AppLiveMapRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/port-authority': typeof AppPortAuthorityRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shipping': typeof AppShippingRoute
  '/app/terminal': typeof AppTerminalRoute
  '/app/truck': typeof AppTruckRoute
  '/app/warehouse': typeof AppWarehouseRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forbidden'
    | '/unauthorized'
    | '/app/admin'
    | '/app/ai'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/audit'
    | '/app/customs'
    | '/app/documents'
    | '/app/live-map'
    | '/app/logistics'
    | '/app/notifications'
    | '/app/port-authority'
    | '/app/reports'
    | '/app/settings'
    | '/app/shipping'
    | '/app/terminal'
    | '/app/truck'
    | '/app/warehouse'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/unauthorized'
    | '/app/admin'
    | '/app/ai'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/audit'
    | '/app/customs'
    | '/app/documents'
    | '/app/live-map'
    | '/app/logistics'
    | '/app/notifications'
    | '/app/port-authority'
    | '/app/reports'
    | '/app/settings'
    | '/app/shipping'
    | '/app/terminal'
    | '/app/truck'
    | '/app/warehouse'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forbidden'
    | '/unauthorized'
    | '/app/admin'
    | '/app/ai'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/audit'
    | '/app/customs'
    | '/app/documents'
    | '/app/live-map'
    | '/app/logistics'
    | '/app/notifications'
    | '/app/port-authority'
    | '/app/reports'
    | '/app/settings'
    | '/app/shipping'
    | '/app/terminal'
    | '/app/truck'
    | '/app/warehouse'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/warehouse': {
      id: '/app/warehouse'
      path: '/warehouse'
      fullPath: '/app/warehouse'
      preLoaderRoute: typeof AppWarehouseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/truck': {
      id: '/app/truck'
      path: '/truck'
      fullPath: '/app/truck'
      preLoaderRoute: typeof AppTruckRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/terminal': {
      id: '/app/terminal'
      path: '/terminal'
      fullPath: '/app/terminal'
      preLoaderRoute: typeof AppTerminalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shipping': {
      id: '/app/shipping'
      path: '/shipping'
      fullPath: '/app/shipping'
      preLoaderRoute: typeof AppShippingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/port-authority': {
      id: '/app/port-authority'
      path: '/port-authority'
      fullPath: '/app/port-authority'
      preLoaderRoute: typeof AppPortAuthorityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistics': {
      id: '/app/logistics'
      path: '/logistics'
      fullPath: '/app/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/live-map': {
      id: '/app/live-map'
      path: '/live-map'
      fullPath: '/app/live-map'
      preLoaderRoute: typeof AppLiveMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customs': {
      id: '/app/customs'
      path: '/customs'
      fullPath: '/app/customs'
      preLoaderRoute: typeof AppCustomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppCustomsRoute: typeof AppCustomsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppLiveMapRoute: typeof AppLiveMapRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPortAuthorityRoute: typeof AppPortAuthorityRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShippingRoute: typeof AppShippingRoute
  AppTerminalRoute: typeof AppTerminalRoute
  AppTruckRoute: typeof AppTruckRoute
  AppWarehouseRoute: typeof AppWarehouseRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppCustomsRoute: AppCustomsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppLiveMapRoute: AppLiveMapRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPortAuthorityRoute: AppPortAuthorityRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShippingRoute: AppShippingRoute,
  AppTerminalRoute: AppTerminalRoute,
  AppTruckRoute: AppTruckRoute,
  AppWarehouseRoute: AppWarehouseRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
